# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Lantern' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KakaoSDKCommon' # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth' # 카카오 로그인
  pod 'KakaoSDKUser' # 사용자 관리

  # Pods for Lantern

  # 네트워크 라이브러리
  pod 'Alamofire'

  # SendBirdCalls
  pod 'SendBirdCalls'

end
